routes:
    index:       
        url: '/admin/?'        
        module: 'Main'
        action: 'index'
    news-insert:
        url: '/admin/news-insert/?'
        module: 'News'
        action: 'insert'
    news-update:
        url: '/admin/news-update-([0-9]+)/?'
        module: 'News'
        action: 'update'
        var:
            - id
    news-delete:
        url: '/admin/news-delete-([0-9]+)/?'
        module: 'News'
        action: 'delete'
        var:
            - id