routes:
    index:       
        url: '/'        
        module: 'Main'
        action: 'index'
        vars:
            - 'section'
    work:
        url: '/work/([-a-z]+)'
        module: 'Work'
        action: 'show'
    news-list:
        url: '/news/?'
        module: 'News'
        action: 'index'
    news-list-page:
        url: '/news/page/([1-9]+)/?'
        module: 'News'
        action: 'index'
        vars:
            - 'page'
    news:
        url: '/news/([0-9]+)/?'
        module: 'News'
        action: 'show'
        vars: 
            - 'id'
    registration:
        url: '/registration/?'
        module: 'Account'
        action: 'registration'