routes:
    index:       
        url: '/'        
        module: 'Main'
        action: 'index'
        vars:
            - 'section'
    work:
        url: '/work/([-a-z]+)'
        module: 'Work'
        action: 'show'
        vars:
            - 'id'